name: build

on:
  push:
    branches: ["*"]
    tags: ["v*"]
  pull_request:

jobs:
  build:
    name: build ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - os: macos-13
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-gnu
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Install Crystal
        if: matrix.target != 'x86_64-pc-windows-gnu'
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest

      - name: Install Crystal (MinGW64)
        if: matrix.target == 'x86_64-pc-windows-gnu'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-crystal
            mingw-w64-x86_64-shards
            mingw-w64-x86_64-htslib

      - name: Set version variables
        shell: bash
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            VERSION=${{ github.ref_name }}
          else
            VERSION="build-$(date +%Y%m%d-%H%M%S)"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "BIN=depth" >> $GITHUB_ENV

      - name: Install native dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libhts-dev

      - name: Install native dependencies (macOS)
        if: startsWith(matrix.os, 'macos')
        run: |
          brew update
          brew install htslib

      - name: Install dependencies
        if: matrix.target != 'x86_64-pc-windows-gnu'
        run: shards install --without-development

      - name: Install dependencies (MinGW64)
        if: matrix.target == 'x86_64-pc-windows-gnu'
        shell: msys2 {0}
        run: shards install --without-development

      - name: Run tests
        if: matrix.target != 'x86_64-pc-windows-gnu'
        run: |
          crystal spec

      - name: Run tests (MinGW64)
        if: matrix.target == 'x86_64-pc-windows-gnu'
        shell: msys2 {0}
        run: |
          crystal spec

      - name: Build on Linux
        if: matrix.target == 'x86_64-unknown-linux-musl'
        shell: bash
        run: |
          mkdir -p bin
          docker run -d --name alpine -v $(pwd):/workspace -w /workspace crystallang/crystal:latest-alpine tail -f /dev/null
          docker exec alpine apk add htslib-static
          docker exec alpine shards install --without-development --release --static
          docker exec alpine shards build --release --static
          docker exec alpine chmod +x bin/$BIN
          ldd bin/$BIN || echo "Static binary (no dynamic dependencies)"
          file bin/$BIN
          bin/$BIN --help
          PKG=depth-${VERSION}-${{ matrix.target }}
          mkdir -p $PKG
          cp bin/$BIN $PKG/
          cp LICENSE $PKG/
          cp README.md $PKG/
          tar czf $PKG.tar.gz $PKG

      - name: Build on macOS
        if: startsWith(matrix.target, 'x86_64-apple-darwin') || startsWith(matrix.target, 'aarch64-apple-darwin')
        shell: bash
        run: |
          shards install --without-development --release
          brew update
          brew install libgc pcre2 htslib
          echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH"
          unset PKG_CONFIG_PATH
          echo "cleared PKG_CONFIG_PATH to avoid openSSL conflicts"
          ln -s $(brew ls libgc | grep libgc.a) .
          ln -s $(brew ls pcre2 | grep libpcre2-8.a) .
          ln -s $(brew ls htslib | grep libhts.a) .
          STATIC_LIBS="-L $(pwd) $(pwd)/libgc.a $(pwd)/libpcre2-8.a $(pwd)/libhts.a"
          shards build --link-flags="$STATIC_LIBS" --release
          chmod +x bin/$BIN
          otool -L bin/$BIN
          if otool -L bin/$BIN | grep homebrew; then
            echo "Error: Homebrew dependencies detected!"
            exit 1
          fi
          echo "Static linking successful"
          file bin/$BIN
          bin/$BIN --help
          PKG=depth-${VERSION}-${{ matrix.target }}
          mkdir -p $PKG
          cp bin/$BIN $PKG/
          cp LICENSE $PKG/
          cp README.md $PKG/
          tar czf $PKG.tar.gz $PKG

      - name: Build on Windows (MinGW64)
        if: matrix.target == 'x86_64-pc-windows-gnu'
        shell: msys2 {0}
        run: |
          shards install --without-development --release
          shards build --release --static
          file bin/$BIN.exe
          bin/$BIN --help
          PKG=depth-${VERSION}-${{ matrix.target }}
          mkdir -p $PKG
          cp bin/$BIN.exe $PKG/
          cp LICENSE $PKG/
          cp README.md $PKG/
          zip -r $PKG.zip $PKG

      - name: Upload artifacts (non-release)
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v4
        with:
          name: depth-${{ matrix.target }}
          path: |
            depth-*.tar.gz
            depth-*.zip

      - name: Upload release assets (release only)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            depth-*.tar.gz
            depth-*.zip
